pfortainer {
    path = /zdata/jails/pfortainer;
    host.hostname = pfortainer;

    ip4.addr = igc3|192.168.10.111/24;
    ip4.addr += lo0|127.0.0.2/8;

    exec.start = "/bin/sh /etc/rc";
    exec.stop  = "/bin/sh /etc/rc.shutdown";
    exec.poststart += "zfs jail pfortainer zdata";
    exec.poststart += "zfs jail pfortainer zboot";
    exec.clean;
    mount.devfs;
    mount.fstab = /etc/fstab.jails/pfortainer;

    allow.mount;
    allow.mount.zfs;
    enforce_statfs = 1;
}
